DirectoryPath: "public/"
IgnoreURLs: 
- "facebook.com"
- "play.google.com"
- "www.superphysics.org"
- "superphysics.org"
- "youtube.com"
- "pantrypoints.com"
- "www.pantrypoints.com"
- "twitter.com"
- "www.linkedin.com"
- "www.googletagmanager.com"
- "pagead2.googlesyndication.com"
- "economictimes.indiatimes.com"
- "wikipedia.org"
- "sorasystem.sirv.com"
- "socioecons.files.wordpress.com"
- "socioecons.wordpress.com"
- "humanityframework.files.wordpress.com"
IgnoreDirectoryMissingTrailingSlash: true